// Sample brand mocks per industry/function. Used as a fallback when a website
// scan returns 403/empty data, or as a quick-pick to demo the Overview page
// with realistic-looking brand identity.
//
// Each mock populates: name, description, primaryColor, secondaryColor,
// keyMessages (first item = hero tagline, rest = value cards), and products.

export const INDUSTRY_OPTIONS = [
  'Healthcare', 'Finance', 'Technology', 'Retail', 'Logistics',
  'Entertainment', 'Sales', 'Marketing', 'Customer Services', 'Customer Insights', 'IT',
  'Product', 'Inventory', 'Event Space', 'Portfolio', 'Fintech App Analytics',
]

export const industryMocks = {
  Healthcare: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/healthcare.svg',
    name: 'Vitalis Health',
    description: 'Coordinated care across hospitals, clinics, and digital touchpoints — keeping patients at the center of every decision.',
    primaryColor: '#0EA5A4',
    secondaryColor: '#0F172A',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/a8af57e1',
    embedThemeId: '3d14a6a9-e7b8-4db2-a3ab-ff8a22263de6',
    keyMessages: [
      'Better health outcomes through connected care.',
      'Patient-first. Every visit, every chart, every choice puts the patient at the center.',
      'Clinically rigorous. Evidence-based protocols backed by ongoing research partnerships.',
      'Always accessible. Telehealth, in-person, and 24/7 nurse triage in one experience.',
    ],
    products: [
      { name: 'Primary Care', description: 'Same-day appointments with dedicated care teams that follow you across visits.' },
      { name: 'Specialty Network', description: 'Cardiology, oncology, orthopedics, and 30+ specialties under one referral system.' },
      { name: 'Vitalis Connect', description: 'Mobile app for visits, prescriptions, lab results, and direct messaging with your care team.' },
    ],
  },
  Finance: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/finance.svg',
    name: 'Meridian Capital',
    description: 'Wealth management and investment advisory built on transparency, fiduciary duty, and long-term client outcomes.',
    primaryColor: '#1E40AF',
    secondaryColor: '#0B1220',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/spreadsheet-income-statement',
    keyMessages: [
      'Your wealth, on your terms.',
      'Fiduciary first. We sit on your side of the table, always.',
      'Clear pricing. No hidden fees, no surprise spreads, no commissions.',
      'Long-term mindset. We invest for decades, not quarters.',
    ],
    products: [
      { name: 'Wealth Advisory', description: 'Personal CFP planners and discretionary portfolio management starting at $250K.' },
      { name: 'Retirement Planning', description: 'Tax-optimized 401(k), IRA, and pension strategies with quarterly rebalancing.' },
      { name: 'Private Markets', description: 'Curated access to PE, real estate, and private credit for accredited investors.' },
    ],
  },
  Technology: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/technology.svg',
    name: 'Helix Labs',
    description: 'Developer-first infrastructure for teams shipping AI-native products — fast pipelines, smart defaults, ridiculous reliability.',
    primaryColor: '#7C3AED',
    secondaryColor: '#0F0B24',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/48d6ad6a',
    embedThemeId: '52fc8ce9-a7d8-44eb-9e84-8f893e8d2e3b',
    keyMessages: [
      'Build software at the speed of thought.',
      'Developer-first. APIs and SDKs designed by engineers who ship every day.',
      'Reliability is a feature. Five nines SLA on every paid tier.',
      'Open by default. Source-available core, transparent roadmap, public RFCs.',
    ],
    products: [
      { name: 'Helix Cloud', description: 'Managed runtime for serverless, containers, and edge functions in 30+ regions.' },
      { name: 'Helix AI', description: 'Inference, fine-tuning, and vector search with one unified API.' },
      { name: 'Helix Observe', description: 'Distributed tracing, logs, and metrics with sub-second query latency.' },
    ],
  },
  Retail: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/retail.svg',
    name: 'Marketline Retail',
    description: 'Modern speciality retail blending in-store experience with mobile-first commerce — 380 stores, one connected brand.',
    primaryColor: '#DB2777',
    secondaryColor: '#1F0717',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/4d28d7ba',
    embedThemeId: 'da3d39e8-642d-4c1e-9781-31c22fc5a4e9',
    keyMessages: [
      'Discover something you love today.',
      'Curated, not crowded. Every SKU earns its shelf space.',
      'Seamless. Buy online, ship from store, return anywhere.',
      'Locally relevant. Each store stocks against neighborhood demand signals.',
    ],
    products: [
      { name: 'Apparel', description: 'Seasonal collections from 200+ established and emerging brands.' },
      { name: 'Home & Lifestyle', description: 'Furniture, decor, and small appliances across every price point.' },
      { name: 'Marketline+', description: 'Membership program with free shipping, early access, and 5% back in rewards.' },
    ],
  },
  Logistics: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/logistics.svg',
    name: 'Routeworks Logistics',
    description: 'Asset-light freight brokerage and last-mile delivery network — moving 4.2M shipments per year across the lower 48.',
    primaryColor: '#0EA5E9',
    secondaryColor: '#0C2540',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/dfcc4445',
    keyMessages: [
      'On time. On budget. On screen.',
      'Real-time visibility. GPS, ETA, and exception alerts on every shipment.',
      '40,000+ vetted carriers. Capacity even when the market gets tight.',
      'Sustainable freight. Carbon reporting and SmartWay-certified network partners.',
    ],
    products: [
      { name: 'Truckload', description: 'Dry van, reefer, and flatbed coverage with dynamic spot-and-contract pricing.' },
      { name: 'LTL & Parcel', description: 'Multi-carrier LTL and parcel optimization with one rating engine.' },
      { name: 'Last-Mile', description: 'Final-mile white-glove delivery and installation in 270 metro markets.' },
    ],
  },
  Entertainment: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/entertainment.svg',
    name: 'Spotlight Studios',
    description: 'Feature film, scripted television, and unscripted entertainment for global streaming audiences — 240 titles and counting.',
    primaryColor: '#F59E0B',
    secondaryColor: '#0A0A0A',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/71f8ccdd',
    embedThemeId: '3df753b0-48a0-4dbb-b0a7-20fc1bd53af9',
    aiConnectionId: 'cb88f8bc-4d53-49d0-9f7e-da80cffffc6a',
    keyMessages: [
      'Stories worth staying up for.',
      'Talent-driven. Long-term creative partnerships with the best writers and directors.',
      'Global. Original productions in 12 languages, distributed in 190+ countries.',
      'Award-magnet. Best Picture, Limited Series, and Animated Feature wins in the last 3 years.',
    ],
    products: [
      { name: 'Feature Films', description: 'Theatrical and streaming releases across drama, comedy, and animation.' },
      { name: 'Scripted TV', description: 'Limited series and ongoing dramas for major streaming platforms.' },
      { name: 'Unscripted', description: 'Reality competition, documentary series, and live event programming.' },
    ],
  },
  Sales: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/sales.svg',
    name: 'Pipeline Pro',
    description: 'AI-powered revenue platform that helps sales teams forecast accurately, coach effectively, and close more deals.',
    primaryColor: '#0891B2',
    secondaryColor: '#0F172A',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/a5dc53af',
    embedThemeId: '54e5e87c-0228-48b6-9bd9-62aca952d76e',
    aiConnectionRole: 'QUERIER',
    keyMessages: [
      'Win more. Guess less.',
      'Forecast with confidence. AI-driven deal scoring with 92% accuracy at submit.',
      'Coach in the moment. Real-time call insights and rep-level conversation analytics.',
      'CRM-native. Drops into Salesforce or HubSpot in under a day.',
    ],
    products: [
      { name: 'Forecasting', description: 'Pipeline inspection, deal scoring, and roll-up forecasting for revenue leaders.' },
      { name: 'Conversation Intel', description: 'Recorded calls, transcripts, and AI-summarized objections and next steps.' },
      { name: 'Rep Coaching', description: 'Personalized scorecards and call libraries for ongoing rep development.' },
    ],
  },
  Marketing: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/marketing.svg',
    name: 'Spectrum Marketing',
    description: 'Full-funnel marketing platform connecting brand campaigns, performance media, and lifecycle CRM in one system.',
    primaryColor: '#C026D3',
    secondaryColor: '#2E1065',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/2ab11ebf',
    embedThemeId: 'da3d39e8-642d-4c1e-9781-31c22fc5a4e9',
    keyMessages: [
      'Every channel. One source of truth.',
      'Unified attribution. See exactly which touchpoints drive revenue.',
      'AI creative. Generate, test, and optimize ads at scale across every platform.',
      'Real-time reporting. Stop waiting for week-end roll-ups.',
    ],
    products: [
      { name: 'Campaigns', description: 'Plan, launch, and report on omnichannel campaigns from a single workspace.' },
      { name: 'Lifecycle CRM', description: 'Email, SMS, and push automations triggered by behavioral signals.' },
      { name: 'Spectrum AI', description: 'Generative creative studio and predictive audience modeling.' },
    ],
  },
  'Customer Services': {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/customer-services.svg',
    name: 'Helpdesk One',
    description: 'AI-augmented customer support platform powering 18,000 companies — chat, voice, email, and self-service in one place.',
    primaryColor: '#06B6D4',
    secondaryColor: '#0E2A47',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/cfdbc45e',
    embedThemeId: '9395eb6e-01d9-4d94-bc26-922370441e05',
    keyMessages: [
      'Faster answers. Happier customers.',
      'AI-first deflection. 60% of tickets resolved without an agent ever touching them.',
      'Omnichannel. Chat, voice, email, social, and SMS in one inbox.',
      'CSAT that climbs. Customers see avg. +14 NPS within 90 days.',
    ],
    products: [
      { name: 'Help Center', description: 'AI-powered self-service portal with auto-suggested articles and live chat fallback.' },
      { name: 'Agent Workspace', description: 'Unified omnichannel inbox with macros, AI summaries, and quality scoring.' },
      { name: 'Voice Cloud', description: 'Cloud-native contact center with skills-based routing and live transcription.' },
    ],
  },
  IT: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/it.svg',
    name: 'Stack IT Solutions',
    description: 'Managed IT services and cybersecurity for mid-market businesses — 24/7 monitoring, SOC2-aligned, never offshored.',
    primaryColor: '#3B82F6',
    secondaryColor: '#111827',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/3fefe5a5',
    embedThemeId: 'e3a2098e-0660-4f5d-a7f2-d44d44150afc',
    keyMessages: [
      'IT that runs itself.',
      '24/7 NOC + SOC. Always on, always domestic.',
      'Predictable pricing. Per-user flat fees, no surprise project bills.',
      'Security-first. SOC2 Type II, PCI, and HIPAA-aligned out of the box.',
    ],
    products: [
      { name: 'Managed IT', description: 'Helpdesk, endpoint management, patching, and asset lifecycle for your whole org.' },
      { name: 'Cybersecurity', description: 'EDR, SIEM, MFA, and 24/7 SOC monitoring with incident response retainers.' },
      { name: 'Cloud Ops', description: 'AWS, Azure, and M365 administration with monthly optimization reviews.' },
    ],
  },
  Product: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/product.svg',
    name: 'Launchpad Product',
    description: 'Product analytics and experimentation platform that helps teams ship features users actually adopt — funnels, cohorts, and A/B tests in one workspace.',
    primaryColor: '#6366F1',
    secondaryColor: '#0B1020',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/c8e617e2',
    embedThemeId: 'e3a2098e-0660-4f5d-a7f2-d44d44150afc',
    keyMessages: [
      'Ship what users love. Skip what they don\'t.',
      'Adoption-first. Track activation, retention, and feature uptake in real time.',
      'Experiment fast. Launch A/B tests and read results without waiting on data science.',
      'One source of truth. Funnels, cohorts, and session replays in a single workspace.',
    ],
    products: [
      { name: 'Product Analytics', description: 'Funnels, retention curves, and cohort analysis across every release.' },
      { name: 'Experimentation', description: 'A/B and multivariate testing with automatic significance and guardrail metrics.' },
      { name: 'Feature Flags', description: 'Progressive rollouts, kill switches, and targeted releases by segment.' },
    ],
  },
  Inventory: {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/inventory.svg',
    name: 'Stockflow Inventory',
    description: 'Real-time inventory and warehouse management across every channel and location — keep the right stock in the right place, always.',
    primaryColor: '#D97706',
    secondaryColor: '#1C1207',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/a964ff65',
    embedThemeId: 'da3d39e8-642d-4c1e-9781-31c22fc5a4e9',
    keyMessages: [
      'Right stock. Right place. Right now.',
      'Live counts. Real-time stock levels across every warehouse and store.',
      'Smart replenishment. Demand forecasting that prevents stockouts and overstock.',
      'Multi-channel. One ledger for ecommerce, retail, and wholesale orders.',
    ],
    products: [
      { name: 'Warehouse Management', description: 'Bin-level tracking, cycle counts, and pick-pack-ship workflows.' },
      { name: 'Demand Planning', description: 'SKU-level forecasting and auto-reorder points tuned to seasonality.' },
      { name: 'Order Routing', description: 'Intelligent fulfillment that ships from the optimal location every time.' },
    ],
  },
  'Event Space': {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/event-space.svg',
    name: 'Atrium Events',
    description: 'Venue and event management platform powering conferences, weddings, and corporate gatherings — bookings, floor plans, and attendee insights in one place.',
    primaryColor: '#BE185D',
    secondaryColor: '#1A0710',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/1691bcc7',
    embedThemeId: '789a1113-065d-45b9-869c-dc5cfa868eaf',
    keyMessages: [
      'Every event, perfectly orchestrated.',
      'Book with confidence. Real-time availability across rooms, halls, and outdoor spaces.',
      'Plan visually. Drag-and-drop floor plans, seating charts, and AV layouts.',
      'Know your guests. Registration, check-in, and attendance analytics in one dashboard.',
    ],
    products: [
      { name: 'Venue Booking', description: 'Calendar-based reservations with dynamic pricing and instant holds.' },
      { name: 'Event Planning', description: 'Floor plans, vendor coordination, and run-of-show timelines for any event.' },
      { name: 'Attendee Insights', description: 'Ticketing, check-in, and post-event engagement reporting.' },
    ],
  },
  'Customer Insights': {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/customer-services.svg',
    name: 'Clarivue',
    description: 'Every customer signal — surveys, support tickets, NPS, and product usage — unified into insights teams can act on in minutes.',
    primaryColor: '#7C3AED',
    secondaryColor: '#0F172A',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/77e54ba7/01KVF13WVR3JQBN7BYBJ249QAA',
    embedThemeId: 'e3a2098e-0660-4f5d-a7f2-d44d44150afc',
    // Pin the embed to the Databricks connection (dialect=databricks).
    aiConnectionId: '2d8f8f05-9c22-4164-9970-b797c0c07d14',
    keyMessages: [
      'Know what your customers feel — before they tell you.',
      'Unified signals. Surveys, tickets, NPS, and product events in one customer view.',
      'Always current. Sentiment and health scores refresh as new interactions land.',
      'Built for action. Route at-risk accounts and standout wins to the right team automatically.',
    ],
    products: [
      { name: 'Voice of Customer', description: 'Centralize surveys, reviews, and support transcripts with automatic theme and sentiment tagging.' },
      { name: 'Health Scores', description: 'Composite account health from usage, sentiment, and support signals — updated in real time.' },
      { name: 'Insight Studio', description: 'Self-serve dashboards and alerts that push customer insights to Slack, email, and your CRM.' },
    ],
  },
  'Portfolio': {
    name: 'Portfolio',
    description: 'Track every holding, allocation, and return in one place — a sleek, real-time view of your entire investment portfolio.',
    primaryColor: '#000000',
    secondaryColor: '#0A0A0A',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/2b5d672c',
    embedThemeId: 'd448b859-1106-459b-851d-8eca69521ff7',
    // Pin the embed to the Snowflake connection.
    aiConnectionId: 'c50411c5-41a2-4a7c-b0dd-27e0d78586f4',
    keyMessages: [
      'Your whole portfolio. One clean, black-on-black view.',
      'Real-time positions. Live prices, P&L, and allocation across every account.',
      'Built for clarity. Performance, risk, and exposure with zero clutter.',
      'Private by design. Your holdings stay yours — no noise, no ads.',
    ],
    products: [
      { name: 'Holdings', description: 'A unified ledger of equities, crypto, and cash across every brokerage and wallet.' },
      { name: 'Performance', description: 'Time-weighted returns, benchmarks, and contribution analysis by position.' },
      { name: 'Allocation', description: 'Live exposure by asset class, sector, and geography with drift alerts.' },
    ],
  },
  'Fintech App Analytics': {
    logoUrl: 'https://fishtankbubble.vercel.app/logos/finance.svg',
    name: 'Fintech App Analytics',
    description: 'Product engagement, payments, and risk in one workspace — every tap, transaction, and cohort measured in real time.',
    primaryColor: '#635BFF',
    secondaryColor: '#0A2540',
    omniApiKey: 'env',
    embedVanityDomain: 'omni.demo.exploreomni.dev',
    embedSecret: 'env',
    embedDashboardPath: '/dashboards/e7560062',
    embedThemeId: '6e3d1fac-2354-452f-a74b-01d15a072fd9',
    // Pin the main Snowflake (ANALYTICS_PROD) connection so the embed grants a
    // role on the connection this dashboard queries (rather than the alphabetical
    // auto-pick, which lands on the unrelated "Food Service Demo" connection).
    aiConnectionId: 'c50411c5-41a2-4a7c-b0dd-27e0d78586f4',
    keyMessages: [
      'Every tap, transaction, and cohort — measured.',
      'Product + revenue in one view. Activation, retention, and LTV beside payment volume.',
      'Real-time funnels. Onboarding, KYC, and first-deposit drop-off as it happens.',
      'Compliant by default. Audit-ready metrics with role-based access.',
    ],
    products: [
      { name: 'Engagement Analytics', description: 'Activation, retention, and feature adoption across your mobile and web app.' },
      { name: 'Payments Insights', description: 'Transaction volume, interchange, and settlement trends by product and region.' },
      { name: 'Risk & Compliance', description: 'KYC funnels, fraud signals, and audit-ready reporting in one workspace.' },
    ],
  },
}
